language: php
os: linux
sudo: required

php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

install: 
  git clone https://github.com/kakekcoding/latihan-mvc.git

before_install:
  sudo apt-get install git
