language: php
os: linux
sudo: required

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then export CFLAGS="-Wno-deprecated-declarations -Wdeclaration-after-statement -Werror"; fi
    - phpize #and lots of other stuff here.
    - make

install: 
  git clone https://github.com/kakekcoding/latihan-mvc.git

before_install:
  sudo apt-get install git
