language: php
os: linux
sudo: required

language: php
php:
- 5.6
- 7.0
env: # important!
matrix:
  include:
  - php: 7.0
    env: KEY=VALUE
  allow_failures:
  - php: 7.0
    env: KEY=VALUE

install: 
  git clone https://github.com/kakekcoding/latihan-mvc.git

before_install:
  sudo apt-get install git
